<?php

namespace Database\Seeders;

use App\Models\Product;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        Product::insert([
            ['name' => 'Hair Dye',   'type'=> 11,  'unit' => 'g',  'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Shampoo',   'type'=> 11,    'unit' => 'g',  'stock' => 1000,'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Hair Spray',  'type'=> 11, 'unit' => 'g',  'stock' => 300, 'created_at' => now(), 'updated_at' => now()],

            // L'Oréal Professionnel INOA
            ['name' => 'INOA 1', 'unit' => 'g', 'type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 3', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 4', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 4.0', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 4.1', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 4.3', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 4.35', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 4.45', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 4.8', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 5', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 5.0', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 5.1', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 5.3', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 5.4', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 5.5', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 5.6', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 5.8', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 6', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 6.0', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 6.1', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 6.11', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 6.13', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 6.3', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 6.34', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 6.4', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 6.45', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 6.6', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 6.60', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 6.8', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 7', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 7.0', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 7.1', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 7.11', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 7.13', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 7.3', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 7.31', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 7.4', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 7.43', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 7.8', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 8', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 8.0', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 8.1', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 8.11', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 8.13', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 8.3', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 8.34', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 8.4', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 8.43', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 8.8', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 9', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 9.0', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 9.1', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 9.11', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 9.13', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 9.2', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 9.21', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 9.3', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 9.31', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 9.82', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 10', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 10.1', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 10.12', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 10.13', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 10.2', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 10.21', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 10.22', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 10.3', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'INOA 10.31', 'unit' => 'g','type'=> 1, 'stock' => 500, 'created_at' => now(), 'updated_at' => now()],

            // Majirel Cool Cover
            ['name' => 'Majirel CC 4',  'unit' => 'g', 'type'=> 2,'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel CC 4.3', 'unit' => 'g', 'type'=> 2,'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel CC 5', 'unit' => 'g', 'type'=> 2,'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel CC 5.1', 'unit' => 'g', 'type'=> 2,'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel CC 5.18', 'unit' => 'g', 'type'=> 2,'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel CC 6', 'unit' => 'g', 'type'=> 2,'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel CC 6.1', 'unit' => 'g', 'type'=> 2,'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel CC 6.17', 'unit' => 'g', 'type'=> 2,'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel CC 6.3', 'unit' => 'g', 'type'=> 2,'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel CC 7', 'unit' => 'g', 'type'=> 2,'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel CC 7.1', 'unit' => 'g', 'type'=> 2,'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel CC 7.11', 'unit' => 'g', 'type'=> 2,'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel CC 7.18', 'unit' => 'g', 'type'=> 2,'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel CC 8', 'unit' => 'g', 'type'=> 2,'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel CC 8.1', 'unit' => 'g', 'type'=> 2,'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel CC 8.11', 'unit' => 'g', 'type'=> 2,'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel CC 9', 'unit' => 'g', 'type'=> 2,'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel CC 9.1', 'unit' => 'g', 'type'=> 2,'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel CC 9.11', 'unit' => 'g', 'type'=> 2,'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel CC 10', 'unit' => 'g', 'type'=> 2,'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel CC 10.1', 'unit' => 'g', 'type'=> 2,'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],

            // Majirel (Standard)
            ['name' => 'Majirel 1', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 3', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 4', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 4.0', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 4.3', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 4.35', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 4.45', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 4.56', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 4.8', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 5', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 5.0', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 5.1', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 5.12', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 5.15', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 5.18', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 5.3', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 5.35', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 5.4', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 5.5', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 5.6', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 5.62', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 5.64', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 5.8', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 6', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 6.0', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 6.01', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 6.1', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 6.11', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 6.13', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 6.23', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 6.3', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 6.32', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 6.34', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 6.35', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 6.4', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 6.45', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 6.6', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 6.60', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 6.62', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 6.64', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 6.65', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 6.8', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 7', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 7.0', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 7.01', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 7.1', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 7.12', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 7.13', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 7.18', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 7.23', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 7.3', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 7.31', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 7.35', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 7.4', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 7.40', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 7.43', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 7.44', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 7.8', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 8', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 8.0', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 8.01', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 8.1', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 8.12', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 8.13', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 8.2', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 8.21', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 8.3', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 8.30', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 8.31', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 8.34', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 8.43', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 8.45', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 8.8', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 9', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 9.0', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 9.01', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 9.1', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 9.12', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 9.13', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 9.21', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 9.22', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 9.3', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 9.31', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 10', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 10.1', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 10.12', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 10.13', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 10.21', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Majirel 10.31', 'unit' => 'g','type'=> 3, 'stock' => 1000, 'created_at' => now(), 'updated_at' => now()],

            // Dia Light
            ['name' => 'Dia Light 4',  'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 5', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 5.07', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 5.1', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 5.11', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 5.12', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 5.20', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 5.31', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 5.4', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 5.66', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 5.8', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 6', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 6.1', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 6.11', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 6.13', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 6.23', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 6.28', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 6.3', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 6.34', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 6.35', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 6.45', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 6.46', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 6.64', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 6.66', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 6.8', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 7', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 7.01', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 7.11', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 7.12', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 7.13', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 7.18', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 7.23', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 7.3', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 7.31', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 7.4', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 7.40', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 7.43', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 7.8', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 8', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 8.1', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 8.11', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 8.18', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 8.21', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 8.23', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 8.24', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 8.28', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 8.3', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 8.34', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 8.43', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 9', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 9.01', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 9.02', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 9.03', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 9.1', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 9.11', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 9.12', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 9.13', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 9.18', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 9.2', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 9.21', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 9.3', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 9.31', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 9.82', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 10.01', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 10.02', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 10.12', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 10.13', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 10.18', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 10.21', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 10.22', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 10.23', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 10.24', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 10.32', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Light 10.82', 'unit' => 'g','type'=> 4, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],

            // Dia Color
            ['name' => 'Dia Color 1',  'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 3', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 4', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 5', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 5.1', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 5.18', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 5.4', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 5.5', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 5.66', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 5.71', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 5.8', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 6', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 6.1', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 6.3', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 6.34', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 6.4', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 6.45', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 6.60', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 6.84', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 7', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 7.13', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 7.18', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 7.3', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 7.31', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 7.4', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 7.44', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 7.8', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 8', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 8.1', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 8.2', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 8.3', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 8.31', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 8.34', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 8.43', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 9', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 9.13', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'Dia Color 9.82', 'unit' => 'g', 'type'=> 5,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],

            //Dia color előhívó
            ['name' => 'D6',  'unit' => 'g','type'=> 6, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'D9', 'unit' => 'g', 'type'=> 6,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'D12', 'unit' => 'g', 'type'=> 6,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],

            //Majinel előhív
            ['name' => 'O3',  'unit' => 'g','type'=> 7, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'O6', 'unit' => 'g', 'type'=> 7,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'O9', 'unit' => 'g', 'type'=> 7,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],

            //INOA előhív
            ['name' => 'IO3', 'unit' => 'g', 'type'=> 8, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'IO6', 'unit' => 'g', 'type'=> 8,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'IO9', 'unit' => 'g', 'type'=> 8,'stock' => 300, 'created_at' => now(), 'updated_at' => now()],

            
            //szőkítő 
            ['name' => 'BS9',  'unit' => 'g', 'type'=> 9, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'BS6', 'unit' => 'g', 'type'=> 9, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
            ['name' => 'BS12', 'unit' => 'g', 'type'=> 9, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],

            //szőkítő por
            ['name' => 'B9',  'unit' => 'g','type'=> 10, 'stock' => 300, 'created_at' => now(), 'updated_at' => now()],
        ]);
    }
}
